version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.5.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-miniconda3-4.5.4-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          - v1-dependencies-miniconda3-4.5.4-

      - run:
          name: install dependencies
          command: |
            pip install -r dev-requirements.txt
            pip install -e .

      - save_cache:
          paths:
            - /opt/conda
          key: v1-dependencies-miniconda3-4.5.4-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run unit tests
          command: |
            py.test tests/

        # Run full installer test
      - setup_remote_docker

      - run:
          #FIXME: Bake this into the base image
          name: install docker
          command: |
            apt-get update

            apt-get install --yes \
                 apt-transport-https \
                 ca-certificates \
                 curl \
                 gnupg2 \
                 software-properties-common

            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/debian \
                $(lsb_release -cs) \
                stable"

            apt-get update

            apt-get install --yes docker-ce

      - run:
          name: build systemd image
          command: |
              docker build -t tljh-systemd .

      - run:
          name: start systemd image
          command: |
            docker run \
              --privileged \
              --detach \
              --name=tljh-systemd-ci \
              tljh-systemd
      - run:
          name: run tljh installer
          command: |
            docker cp . tljh-systemd-ci:/srv/src
            docker exec -it tljh-systemd-ci bash /srv/src/installer/install.bash

      - run:
          name: check jupyterhub is up
          command: |
            docker exec -it tljh-systemd-ci curl -L --fail http://localhost
