version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.5.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-miniconda3-4.5.4-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          - v1-dependencies-miniconda3-4.5.4-

      - run:
          name: install dependencies
          command: |
            pip install -r dev-requirements.txt
            pip install -e .

      - save_cache:
          paths:
            - /opt/conda
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run tests
          command: |
            sudo venv/bin/py.test tests/
