version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.5.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-miniconda3-4.5.4-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          - v1-dependencies-miniconda3-4.5.4-

      - run:
          name: install dependencies
          command: |
            pip install -r dev-requirements.txt
            pip install -e .

      - save_cache:
          paths:
            - /opt/conda
          key: v1-dependencies-miniconda3-4.5.4-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}

      - run:
          name: run unit tests
          command: |
            py.test tests/

        # Run full installer test
      - setup_remote_docker

      - run:
          name: build docker image
          command: |
            docker build -t tljh-systemd .

      - run:
          name: start docker image
          command: |
            docker run \
              --privileged \
              --detach \
              --name=tljh-dev \
              tljh-systemd
